# docker-compose.yml
version: '3.8'

services:
  webapp:
    # IMPORTANT: We now specify the image to pull, we don't build it here.
    # Replace 'adhamelgohary' with your GitHub username (it's case-sensitive).
    # Replace 'mosla-pionners' with your repository name.
    image: ghcr.io/adhamelgohary/mosla-pionners:latest
    container_name: mosla_webapp
    restart: always
    ports:
      - "12345:12345"
    volumes:
      - uploads_data:/app/static/uploads
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mosla_db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

  # NEW: Add the watchtower service
  watchtower:
    image: containrrr/watchtower
    container_name: mosla_watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 # Check for new images every 300 seconds (5 minutes)

volumes:
  db_data:
  uploads_data: