version: '3.8'

services:
  webapp:
    image: adhamelgohary02/mosla-pioneers:${TAG:-latest}
    ports:
      - "80:8000"
    volumes:
      - uploads:/app/static/uploads
    environment:
      # These are set by the entrypoint.sh script now
      # - FLASK_SECRET_KEY_FILE=/run/secrets/flask_secret_key
      # - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_HOST=db
      - DB_NAME=mosla_db
      - DB_USER=mosla_user
    secrets:
      - db_password
      - flask_secret_key
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      # THIS IS THE CRITICAL FIX:
      # It tells the container to use the env var passed by the deploy script.
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD_SECRET} 
      - MYSQL_DATABASE=mosla_db
      - MYSQL_USER=mosla_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password # This is for creating the user
    secrets:
      - db_password
      # We still mount the root password for the healthcheck
      - db_root_password
    healthcheck:
      # This healthcheck is also robust
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=`cat /run/secrets/db_root_password`"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # (Optional but recommended) phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
    deploy:
      replicas: 1

secrets:
  db_password:
    external: true
  db_root_password:
    external: true
  flask_secret_key:
    external: true

volumes:
  db_data:
  uploads: