# docker-compose.yml

version: '3.8'

services:
  webapp:
    image: adhamelgohary02/mosla-pioneers:${TAG:-latest}
    ports:
      - "8000:8000"
    environment:
      FLASK_SECRET_KEY: "your_super_secret_key_here"
      DB_HOST: db  # <-- CRITICAL: Use the service name of the database
      DB_USER: mosla_user
      DB_PASSWORD: Moslla@20@25
      DB_NAME: mosla_db

    depends_on:
      - db
    volumes:
      - uploads:/app/static/uploads
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      # These now read variables from the shell where 'docker stack deploy' is run
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=mosla_db
      - MYSQL_USER=mosla_user
      - MYSQL_PASSWORD=${DB_PASSWORD}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      # This also reads the variable from the shell
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    deploy:
      replicas: 1

# No more 'secrets' block at the bottom
volumes:
  db_data:
  uploads: