version: '3.8'

services:
  webapp:
    # This image name must match what you build in your GitHub Actions workflow
    image: your_dockerhub_username/mosla-pioneers:${TAG:-latest}
    ports:
      # Map port 80 on the VPS to port 8000 in the container (where Gunicorn listens)
      - "80:8000"
    volumes:
      # Mount a volume to persist uploaded files across deployments
      - uploads:/app/static/uploads
    environment:
      # --- Flask & App Settings ---
      - FLASK_SECRET_KEY_FILE=/run/secrets/flask_secret_key # More secure way
      - FLASK_SESSION_LIFETIME=7200 # 2 hours
      # --- Database Connection Settings ---
      - DB_HOST=db # The service name of the database container
      - DB_NAME=mosla_pioneers
      - DB_USER=mosla_user
      - DB_PASSWORD_FILE=/run/secrets/db_password # Path to the secret file
      # --- Mail Settings ---
      - MAIL_SERVER=smtp.example.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=True
      - MAIL_USERNAME=your-email@example.com
      - MAIL_PASSWORD_FILE=/run/secrets/mail_password # Use a secret for mail pass
    secrets:
      - db_password
      - flask_secret_key
      - mail_password
    depends_on:
      - db # Wait for the db service to be ready before starting
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: mysql:8.0
    volumes:
      # Persist the entire MySQL database data directory
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=mosla_pioneers
      - MYSQL_USER=mosla_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
      - db_root_password

# Define the secrets. 'external: true' means we will create them manually or via script on the host.
secrets:
  db_password:
    external: true
  db_root_password:
    external: true
  flask_secret_key:
    external: true
  mail_password:
    external: true

# Define the named volumes for persistent data
volumes:
  db_data:
  uploads: