version: '3.8'

services:
  webapp:
    image: adhamelgohary02/mosla-pioneers:${TAG:-latest}
    ports:
      - "80:8000"
    volumes:
      - uploads:/app/static/uploads
    environment:
      # --- Flask & App Settings ---
      - FLASK_SECRET_KEY_FILE=/run/secrets/flask_secret_key
      - FLASK_SESSION_LIFETIME=7200
      # --- Database Connection Settings ---
      - DB_HOST=db
      - DB_NAME=mosla_db
      - DB_USER=mosla_user
      - DB_PASSWORD_FILE=/run/secrets/db_password
      # --- Mail Settings (optional, but good to have) ---
      # Ensure you have these secrets if your app needs to send email
      - MAIL_PASSWORD_FILE=/run/secrets/mail_password
      # You might need other MAIL_* vars here depending on your app.py setup
    secrets:
      - db_password
      - flask_secret_key
      - mail_password # Add mail_password secret here
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=mosla_db
      - MYSQL_USER=mosla_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
      - db_root_password
    healthcheck:
      # This command correctly reads the password from the secret file
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=`cat /run/secrets/db_root_password`"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

# Define all the secrets your services will use.
# 'external: true' means they are created on the VPS by your GitHub Actions script.
secrets:
  db_password:
    external: true
  db_root_password:
    external: true
  flask_secret_key:
    external: true
  mail_password:
    external: true

# Define the named volumes for persistent data.
volumes:
  db_data:
  uploads: