# docker-compose.yml for manual deployment

version: '3.8'

services:
  webapp:
    # This is just a name. It refers to the image we will load manually.
    image: adhamelgohary/mosla-pionners:latest
    container_name: mosla_webapp
    restart: always
    ports:
      - "12345:12345"
    volumes:
      - uploads_data:/app/static/uploads
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: mosla_db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

volumes:
  db_data:
  uploads_data: