# Name of the workflow
name: Deploy to VPS

# Trigger this workflow on every push to the 'main' branch
on:
  push:
    branches: [ main ]

# Define the jobs to run
jobs:
  deploy:
    # Run this job on a fresh Ubuntu virtual machine provided by GitHub
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: SSH into the VPS and run the deployment script
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sh ~/deploy.sh