name: Deploy Mosla Pioneers App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mosla-pioneers:${{ github.sha }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Create secrets on the server if they don't exist
            # This is idempotent and safe to run on every deployment
            echo "${{ secrets.DB_PASSWORD }}" | docker secret create db_password - || true
            echo "${{ secrets.DB_ROOT_PASSWORD }}" | docker secret create db_root_password - || true
            echo "${{ secrets.FLASK_SECRET_KEY }}" | docker secret create flask_secret_key - || true
            echo "${{ secrets.MAIL_PASSWORD }}" | docker secret create mail_password - || true

            # Set the TAG environment variable to the Git commit SHA
            export TAG=${{ github.sha }}

            # Deploy the stack. This command updates the service with the new image.
            docker stack deploy --compose-file docker-compose.yml --with-registry-auth mosla-stack