# .github/workflows/deploy.yml

name: Deploy Mosla Pioneers App with .env

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- THIS IS THE KEY CHANGE ---
      - name: Create .env file
        run: |
          echo "FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_NAME=mosla_db" >> .env
          echo "DB_USER=mosla_user" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "FLASK_SESSION_LIFETIME=86400" >> .env
          echo "--- Created .env file from secrets ---"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: adhamelgohary02/mosla-pioneers:${{ github.sha }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            # Set environment variables for docker-compose on the server
            export TAG=${{ github.sha }}
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export DB_ROOT_PASSWORD="${{ secrets.DB_ROOT_PASSWORD }}"

            # Navigate to the app directory and pull latest compose file
            APP_DIR=~/mosla-pioneers-app
            if [ ! -d "$APP_DIR" ]; then
              git clone "https://AdhamElgohary:${{ secrets.GH_PAT }}@github.com/AdhamElgohary/Mosla-Pionners.git" "$APP_DIR"
            fi
            cd "$APP_DIR"
            git pull origin main

            # Deploy the stack
            # Docker Compose will use the exported variables for the db service
            echo "Deploying stack with image tag: $TAG"
            docker stack deploy --compose-file docker-compose.yml --with-registry-auth mosla-stack